/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install and is checked in here
// so TypeScript works immediately after dependency installation.
